# Generated by Django 4.0.4 on 2022-06-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_discription',
            new_name='tag_description',
        ),
    ]
